name: backend_deployment

on:
  push:
    branches: [master]

jobs:
  docker_cicd:
    name: Build & Deploy to Lambda
    runs-on: ubuntu-latest

    steps:
    # 1 – Check out code
    - uses: actions/checkout@v4

    # 2 – Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id:     ${{ secrets.AWS_CICD_ACCESS }}
        aws-secret-access-key: ${{ secrets.AWS_CICD_SECRET }}
        aws-region:            us-east-1

    # 3 – Authenticate Docker with Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 4 – Build the image and push it to ECR
    - name: Build & push image
      working-directory: RecommendationEngine   # folder with your Dockerfile
      env:
        REGISTRY:   ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ secrets.AWS_REPOSITORY }}
        IMAGE_TAG:  ${{ github.sha }}
      run: |
        set -euo pipefail
        docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -t $REGISTRY/$REPOSITORY:latest \
          .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:latest

    # 5 – Update the Lambda function
    - name: Update Lambda function
      env:
        REGISTRY:   ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ secrets.AWS_REPOSITORY }}
        IMAGE_TAG:  ${{ github.sha }}
        LAMBDA_FN:  ${{ secrets.LAMBDA_FUNCTION_NAME }}
      run: |
        aws lambda update-function-code \
          --function-name $LAMBDA_FN \
          --image-uri $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          --region us-east-1
